import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Zentro Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen scroll-smooth antialiased`}>
        {children}
      </body>
    </html>
  );
}
