import type { Metadata } from "next";
import "./globals.css";
import TanstackQueryProvider from "~/components/providers/tanstack-query";

export const metadata: Metadata = {
  title: "Zentro Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`scroll-smooth bg-blue-50/80 antialiased`}>
        <TanstackQueryProvider>{children}</TanstackQueryProvider>
      </body>
    </html>
  );
}
