import type { Metadata } from "next";
import "./globals.css";
import TanstackQueryProvider from "~/components/providers/tanstack-query";
import { AuthProvider } from "~/components/providers/auth";

export const metadata: Metadata = {
  title: "Zentro Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`scroll-smooth bg-blue-50/80 antialiased`}>
        <TanstackQueryProvider>
          <AuthProvider>{children}</AuthProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
